#' responseReturn
#'
#' @param raw the chatresponse to return
#' @param type  Default is 1, which cats the output, type 2 is unchanged and type 3 returns the output to the clipboard and returns TRUE
#'
#' @importFrom clipr read_clip
#'
#' @return A character value with the response generated by LLM.
#'
#'
responseReturn <- function(raw, type) {
  if (type == 1) {
    # Function 'cat' is used to concatenate 'raw' and return the result
    return(cat(raw))
  } else if (type == 2) {
    # Here, 'raw' is returned without any modification
    return(raw)
  } else if (type == 3) {
    # Here, 'raw' data is written to the clipboard
    clipr::write_clip(raw, allow_non_interactive = TRUE)
    return(TRUE)
  }
}
