#' responseReturn
#'
#' @param raw the chatresponse to return
#'
#' @importFrom clipr read_clip
#'
#' @return A character value with the response generated by Large Language Model.
#'
#'
responseReturn <- function(raw) {

    # Write 'raw' data to the clipboard
    clipr::write_clip(raw, allow_non_interactive = TRUE)

    return(raw)

}
